// Code generated by "go-enum -type=MatcherType -linecomment -sql=false"; DO NOT EDIT.

package match

import (
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MatcherUnknown-0]
	_ = x[MatcherRegex-1]
	_ = x[MatcherPattern-2]
	_ = x[MatcherPatternRegex-3]
	_ = x[MatcherComparison-4]
}

const _MatcherType_name = "unknownregexpatternpatternregexcomparison"

var _MatcherType_index = [...]uint8{0, 7, 12, 19, 31, 41}

func _() {
	var _nil_MatcherType_value = func() (val MatcherType) { return }()

	// An "cannot convert MatcherType literal (type MatcherType) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_MatcherType_value
}

func (i MatcherType) String() string {
	if i < 0 || i >= MatcherType(len(_MatcherType_index)-1) {
		return "MatcherType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MatcherType_name[_MatcherType_index[i]:_MatcherType_index[i+1]]
}

// New returns a pointer to a new addr filled with the MatcherType value passed in.
func (i MatcherType) New() *MatcherType {
	clone := i
	return &clone
}

var _MatcherType_values = []MatcherType{0, 1, 2, 3, 4}

var _MatcherType_name_to_values = map[string]MatcherType{
	_MatcherType_name[0:7]:   0,
	_MatcherType_name[7:12]:  1,
	_MatcherType_name[12:19]: 2,
	_MatcherType_name[19:31]: 3,
	_MatcherType_name[31:41]: 4,
}

// ParseMatcherTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseMatcherTypeString(s string) (MatcherType, error) {
	if val, ok := _MatcherType_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MatcherType values", s)
}

// MatcherTypeValues returns all values of the enum
func MatcherTypeValues() []MatcherType {
	return _MatcherType_values
}

// IsAMatcherType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MatcherType) Registered() bool {
	for _, v := range _MatcherType_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_MatcherType_value = func() (val MatcherType) { return }()

	// An "cannot convert MatcherType literal (type MatcherType) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_MatcherType_value

	// An "cannot convert MatcherType literal (type MatcherType) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_MatcherType_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for MatcherType
func (i MatcherType) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for MatcherType
func (i *MatcherType) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseMatcherTypeString(string(data))
	return err
}

func _() {
	var _nil_MatcherType_value = func() (val MatcherType) { return }()

	// An "cannot convert MatcherType literal (type MatcherType) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_MatcherType_value

	// An "cannot convert MatcherType literal (type MatcherType) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_MatcherType_value
}

// MarshalJSON implements the json.Marshaler interface for MatcherType
func (i MatcherType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MatcherType
func (i *MatcherType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MatcherType should be a string, got %s", data)
	}

	var err error
	*i, err = ParseMatcherTypeString(s)
	return err
}

func _() {
	var _nil_MatcherType_value = func() (val MatcherType) { return }()

	// An "cannot convert MatcherType literal (type MatcherType) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_MatcherType_value

	// An "cannot convert MatcherType literal (type MatcherType) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_MatcherType_value
}

// MarshalText implements the encoding.TextMarshaler interface for MatcherType
func (i MatcherType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MatcherType
func (i *MatcherType) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseMatcherTypeString(string(text))
	return err
}

//func _() {
//	var _nil_MatcherType_value = func() (val MatcherType) { return }()
//
//	// An "cannot convert MatcherType literal (type MatcherType) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_MatcherType_value
//
//	// An "cannot convert MatcherType literal (type MatcherType) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_MatcherType_value
//}

// MarshalYAML implements a YAML Marshaler for MatcherType
func (i MatcherType) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for MatcherType
func (i *MatcherType) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseMatcherTypeString(s)
	return err
}

// MatcherTypeSliceContains reports whether sunEnums is within enums.
func MatcherTypeSliceContains(enums []MatcherType, sunEnums ...MatcherType) bool {
	var seenEnums = map[MatcherType]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// MatcherTypeSliceContainsAny reports whether any sunEnum is within enums.
func MatcherTypeSliceContainsAny(enums []MatcherType, sunEnums ...MatcherType) bool {
	var seenEnums = map[MatcherType]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
